name: Setup Python Environment
description: Set Python with its dependencies for note-api

inputs:
  python-version:
    description: Used Python
    required: true
    default: "3.14.2"
  cache-key-suffix:
    description: Cache key for different job
    required: false
    default: ''

outputs:
  cache-dir:
    description: Path to pip cache
    value: ${{ steps.cache-dir.outputs.dir }}
runs:
  using: composite
  steps:
    - name: Set Python ${{ inputs.python-version}}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Get pip cache dir
      id: cache-dir
      shell: bash
      run: |
        echo "dir=$(pip3 cache dir)" >> $GITHUB_OUTPUT
      
    - name: Caching pip dependencies
      id: cache-dependencies
      uses: actions/cache@v5
      with:
        path: ${{ steps.cache-dir.outputs.dir }}
        key: ${{runner.os }}-pip-${{ inputs.python-version }}-${{ hashFiles('**/requirements.txt') }}-${{ inputs.cache-key-suffix }}
        restore-keys:
          ${{ runner.os }}-pip-${{ inputs.python-version }}-${{ hashFiles('**/requirements.txt') }}
          ${{ runner.os }}-pip-${{ inputs.python-version }}-
          ${{ runner.os }}-pip-

    - name: Install Dependencies
      shell: bash
      run: |
        if [ -f flask_app/requirements.txt ]; then
          echo "Found requirements.txt"
          pip3 install -r flask_app/requirements.txt
        else
          echo "No requirements was found!"
        fi
  
